name: Python-EB

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual triggering
  
env:
  ELASTIC_BEANSTALK_NAME: simple-weather
  ELASTIC_BEANSTALK_ENV_NAME: simple-weather-env

jobs:
  zip-files:
    runs-on: ubuntu-latest

    outputs:
      artifact_name: ${{ steps.artifact-name.outputs.artifact_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate artifact file name
        id: artifact-name
        run: |
          # Generate a unique name using the current date and time
          ARTIFACT_NAME="simple-weather_$(date +'%Y-%m-%d_%H-%M-%S')"
          echo "Generated artifact file name: $ARTIFACT_NAME"
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
  
      - name: Zip selected files
        run: |
          # Use the generated zip file name
          zip -r ${{ steps.artifact-name.outputs.artifact_name }} application.py staticcss statichtml .ebextensions
          echo "Zipped files to ${{ steps.artifact-name.outputs.artifact_name }}.zip"
  
      - name: Upload zip file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.artifact_name }}
          path: ${{ steps.artifact-name.outputs.artifact_name }}.zip
  

  deploy:
    runs-on: ubuntu-latest
    needs: zip-files

    steps:
    - uses: actions/download-artifact@v4.1.7
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        artifact-name: ${{ needs.zip-files.outputs.artifact_name }}

    - name: Deploy
      run: |
        aws s3 cp ${{ needs.zip-files.outputs.artifact_name }}/${{ needs.zip-files.outputs.artifact_name }}.zip s3://elasticbeanstalk-eu-west-2-${{ secrets.AWS_ACCOUNT_ID }}/github-actions-artifacts/
        aws elasticbeanstalk create-application-version --application-name $ELASTIC_BEANSTALK_NAME --version-label ${{github.run_id}} --description ${{github.run_id}} --source-bundle S3Bucket="elasticbeanstalk-eu-west-2-${{ secrets.AWS_ACCOUNT_ID }}",S3Key=github-actions-artifacts/${{ needs.zip-files.outputs.artifact_name }}.zip
        aws elasticbeanstalk update-environment --application-name $ELASTIC_BEANSTALK_NAME --environment-name $ELASTIC_BEANSTALK_ENV_NAME --version-label ${{ needs.zip-files.outputs.artifact_name }}
        aws elasticbeanstalk wait environment-updated --application-name $ELASTIC_BEANSTALK_NAME --environment-name $ELASTIC_BEANSTALK_ENV_NAME

