name: Python-EB

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate zip file name
        id: zip-name
        run: |
          # Generate a unique name using the current date and time
          ZIP_NAME="simple-weather_$(date +'%Y-%m-%d_%H-%M-%S')"
          echo "Generated zip file name: $ZIP_NAME"
          echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: Zip selected files
        run: |
          # Use the generated zip file name
          zip -r ${{ steps.zip-name.outputs.zip_name }} application.py staticcss statichtml .ebextensions

      - name: Upload zip file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.zip-name.outputs.zip_name }}
          path: ${{ steps.zip-name.outputs.zip_name }}
